version: "3.0"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    image: nginx:0.0.1
    restart: always
    ports:
      - "8084:80"
      - target: 80
        published: 8084
        protocol: tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf