version: "3.0"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    image: nginx:0.0.1
    restart: always
    ports:
      - target: 80
        published: 8081
        protocol: tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf